minor_changes:
- "docker_secret - ``data`` can now accept Base64-encoded data via the new ``data_is_b64`` option.
   This allows to pass binary data or JSON data in unmodified form. (https://github.com/ansible/ansible/issues/35119)"
